workflows:
  ios-workflow:
    name: iOS Build
    max_build_duration: 60
    environment:
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install and Setup iOS Properly
        script: |
          npm install
          # Capacitor için gerekli www klasörünü garantiye alıyoruz
          mkdir -p www
          echo "<html><body>Game</body></html>" > www/index.html
          
          # iOS platformunu sıfırdan ekliyoruz
          npx cap add ios
          npx cap sync ios
          
          # Podfile'ın olduğu dizine girip pod kuruyoruz
          cd ios/App
          pod install
      - name: Build ipa
        script: |
          cd ios/App
          WORKSPACE=$(find . -name "*.xcworkspace" | head -n 1)
          SCHEME=$(basename "$WORKSPACE" .xcworkspace)
          xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -sdk iphoneos -configuration Release archive -archivePath build/App.xcarchive
          xcodebuild -exportArchive -archivePath build/App.xcarchive -exportOptionsPlist exportOptions.plist -exportPath build/
