workflows:
  ios-workflow:
    name: iOS Build
    max_build_duration: 60
    environment:
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install and Setup iOS
        script: |
          npm install
          npx cap add ios
          cd ios/App
          pod install
      - name: Build ipa
        script: |
          cd ios/App
          WORKSPACE=$(find . -name "*.xcworkspace" | head -n 1)
          SCHEME=$(basename "$WORKSPACE" .xcworkspace)
          xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -sdk iphoneos -configuration Release archive -archivePath build/App.xcarchive
          xcodebuild -exportArchive -archivePath build/App.xcarchive -exportOptionsPlist exportOptions.plist -exportPath build/
